import { Destination } from '@/types';

export const mockDestinations: Destination[] = [
  {
    id: 'dubai-uae',
    name: 'Dubai',
    country: 'UAE',
    coordinates: { lat: 25.2048, lng: 55.2708, label: '' },
    description: 'City of Gold',
    bestTimeToVisit: 'Nov-Mar',
    currency: 'AED',
    language: 'Arabic/English',
    flightTime: '5h from Dhaka',
    visaRequirement: 'Visa required',
    popularAttractions: ['Desert Safari', 'Burj Khalifa', 'Dubai Mall', 'Dubai Marina'],
    startingPrice: 45000,
    image: { src: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop', alt: 'Image' },
    featured: true
  },
  {
    id: 'kuala-lumpur-malaysia',
    name: 'Malaysia',
    country: 'Malaysia',
    coordinates: { lat: 3.1390, lng: 101.6869, label: '' },
    description: 'Truly Asia',
    bestTimeToVisit: 'Mar-Oct',
    currency: 'MYR',
    language: 'Malay/English',
    flightTime: '4h',
    visaRequirement: 'No visa for many',
    popularAttractions: ['Petronas Towers', 'Langkawi', 'Penang'],
    startingPrice: 35000,
    image: { src: 'https://images.unsplash.com/photo-1596422846543-74c6fc0e241e?w=800&h=600&fit=crop', alt: 'Image' },
    featured: true
  },
  {
    id: 'bangkok-thailand',
    name: 'Thailand',
    country: 'Thailand',
    coordinates: { lat: 13.7563, lng: 100.5018, label: '' },
    description: 'Land of Smiles',
    bestTimeToVisit: 'Nov-Feb',
    currency: 'THB',
    language: 'Thai',
    flightTime: '3h',
    visaRequirement: 'Visa on arrival',
    popularAttractions: ['Grand Palace', 'Phi Phi', 'Chiang Mai'],
    startingPrice: 30000,
    image: { src: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&h=600&fit=crop', alt: 'Image' },
    featured: true
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    coordinates: { lat: 1.3521, lng: 103.8198, label: '' },
    description: 'Lion City',
    bestTimeToVisit: 'Year-round',
    currency: 'SGD',
    language: 'English',
    flightTime: '4h',
    visaRequirement: 'Visa required',
    popularAttractions: ['Marina Bay', 'Gardens by the Bay', 'Sentosa'],
    startingPrice: 55000,
    image: { src: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&h=600&fit=crop', alt: 'Image' },
    featured: false
  },
  {
    id: 'istanbul-turkey',
    name: 'Turkey',
    country: 'Turkey',
    coordinates: { lat: 41.0082, lng: 28.9784, label: '' },
    description: 'Where East Meets West',
    bestTimeToVisit: 'Apr-Jun Sep-Nov',
    currency: 'TRY',
    language: 'Turkish',
    flightTime: '8h',
    visaRequirement: 'E-visa',
    popularAttractions: ['Hagia Sophia', 'Cappadocia', 'Grand Bazaar'],
    startingPrice: 65000,
    image: { src: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=600&fit=crop', alt: 'Image' },
    featured: true
  },
  {
    id: 'maldives',
    name: 'Maldives',
    country: 'Maldives',
    coordinates: { lat: 3.2028, lng: 73.2207, label: '' },
    description: 'Paradise on Earth',
    bestTimeToVisit: 'Nov-Apr',
    currency: 'MVR',
    language: 'Dhivehi',
    flightTime: '3h',
    visaRequirement: 'Visa on arrival',
    popularAttractions: ['Overwater villas', 'Snorkeling', 'Island hopping'],
    startingPrice: 85000,
    image: { src: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&h=600&fit=crop', alt: 'Image' },
    featured: false
  },
  {
    id: 'riyadh-saudi-arabia',
    name: 'Saudi Arabia',
    country: 'Saudi Arabia',
    coordinates: { lat: 24.7136, lng: 46.6753, label: '' },
    description: 'Kingdom of Heritage',
    bestTimeToVisit: 'Oct-Mar',
    currency: 'SAR',
    language: 'Arabic',
    flightTime: '5h',
    visaRequirement: 'Visa required',
    popularAttractions: ['Umrah', 'Hajj', 'AlUla', 'Riyadh'],
    startingPrice: 75000,
    image: { src: 'https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?w=800&h=600&fit=crop', alt: 'Image' },
    featured: false
  },
  {
    id: 'bali-indonesia',
    name: 'Indonesia (Bali)',
    country: 'Indonesia',
    coordinates: { lat: -8.3405, lng: 115.0920, label: '' },
    description: 'Island of Gods',
    bestTimeToVisit: 'Apr-Oct',
    currency: 'IDR',
    language: 'Indonesian',
    flightTime: '7h',
    visaRequirement: 'Visa on arrival',
    popularAttractions: ['Ubud', 'Uluwatu', 'Rice Terraces'],
    startingPrice: 40000,
    image: { src: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=600&fit=crop', alt: 'Image' },
    featured: false
  },
  {
    id: 'tokyo-japan',
    name: 'Japan',
    country: 'Japan',
    coordinates: { lat: 35.6762, lng: 139.6503, label: '' },
    description: 'The Land of Rising Sun',
    bestTimeToVisit: 'Mar-May Sep-Nov',
    currency: 'JPY',
    language: 'Japanese',
    flightTime: '8h',
    visaRequirement: 'Visa required',
    popularAttractions: ['Shibuya', 'Mount Fuji', 'Kyoto'],
    startingPrice: 95000,
    image: { src: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=600&fit=crop', alt: 'Image' },
    featured: false
  }
];
