export interface CountryCode {
  code: string;
  name: string;
  country: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  { country: "US", name: "United States", code: "+1", flag: "🇺🇸" },
  { country: "BD", name: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { country: "GB", name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { country: "CA", name: "Canada", code: "+1", flag: "🇨🇦" },
  { country: "AE", name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { country: "SA", name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { country: "MY", name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { country: "SG", name: "Singapore", code: "+65", flag: "🇸🇬" },
  { country: "TH", name: "Thailand", code: "+66", flag: "🇹🇭" },
  { country: "IN", name: "India", code: "+91", flag: "🇮🇳" },
  { country: "PK", name: "Pakistan", code: "+92", flag: "🇵🇰" },
  { country: "AU", name: "Australia", code: "+61", flag: "🇦🇺" },
  { country: "DE", name: "Germany", code: "+49", flag: "🇩🇪" },
  { country: "FR", name: "France", code: "+33", flag: "🇫🇷" },
  { country: "IT", name: "Italy", code: "+39", flag: "🇮🇹" },
  { country: "ES", name: "Spain", code: "+34", flag: "🇪🇸" },
  { country: "TR", name: "Turkey", code: "+90", flag: "🇹🇷" },
  { country: "QA", name: "Qatar", code: "+974", flag: "🇶🇦" },
  { country: "KW", name: "Kuwait", code: "+965", flag: "🇰🇼" },
  { country: "OM", name: "Oman", code: "+968", flag: "🇴🇲" },
  { country: "BH", name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { country: "JP", name: "Japan", code: "+81", flag: "🇯🇵" },
  { country: "CN", name: "China", code: "+86", flag: "🇨🇳" },
  { country: "KR", name: "South Korea", code: "+82", flag: "🇰🇷" },
  { country: "ID", name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { country: "PH", name: "Philippines", code: "+63", flag: "🇵🇭" },
  { country: "VN", name: "Vietnam", code: "+84", flag: "🇻🇳" },
  { country: "NP", name: "Nepal", code: "+977", flag: "🇳🇵" },
  { country: "LK", name: "Sri Lanka", code: "+94", flag: "🇱🇰" },
  { country: "MV", name: "Maldives", code: "+960", flag: "🇲🇻" },
  { country: "EG", name: "Egypt", code: "+20", flag: "🇪🇬" },
  { country: "ZA", name: "South Africa", code: "+27", flag: "🇿🇦" },
  { country: "NG", name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { country: "BR", name: "Brazil", code: "+55", flag: "🇧🇷" },
  { country: "MX", name: "Mexico", code: "+52", flag: "🇲🇽" },
  { country: "NZ", name: "New Zealand", code: "+64", flag: "🇳🇿" },
  { country: "IE", name: "Ireland", code: "+353", flag: "🇮🇪" },
  { country: "NL", name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { country: "CH", name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { country: "SE", name: "Sweden", code: "+46", flag: "🇸🇪" },
  { country: "NO", name: "Norway", code: "+47", flag: "🇳🇴" },
  { country: "DK", name: "Denmark", code: "+45", flag: "🇩🇰" },
  { country: "FI", name: "Finland", code: "+358", flag: "🇫🇮" },
  { country: "PL", name: "Poland", code: "+48", flag: "🇵🇱" },
  { country: "PT", name: "Portugal", code: "+351", flag: "🇵🇹" },
  { country: "GR", name: "Greece", code: "+30", flag: "🇬🇷" },
  { country: "RU", name: "Russia", code: "+7", flag: "🇷🇺" },
];
