export enum ServiceCategory {
  VISA = 'VISA',
  TOUR = 'TOUR',
  FLIGHT = 'FLIGHT',
  HOTEL = 'HOTEL',
  INSURANCE = 'INSURANCE',
  TRANSFER = 'TRANSFER',
  CUSTOM = 'CUSTOM',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  FOLLOW_UP = 'FOLLOW_UP',
  QUOTATION_SENT = 'QUOTATION_SENT',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  CONVERTED = 'CONVERTED',
  CLOSED = 'CLOSED',
  LOST = 'LOST',
}

export enum LeadPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum VisaApplicationStatus {
  SUBMITTED = 'SUBMITTED',
  DOCUMENTS_REVIEW = 'DOCUMENTS_REVIEW',
  DOCUMENTS_VERIFIED = 'DOCUMENTS_VERIFIED',
  PROCESSING = 'PROCESSING',
  EMBASSY_PROCESSING = 'EMBASSY_PROCESSING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PASSPORT_READY = 'PASSPORT_READY',
  COMPLETED = 'COMPLETED',
}

export enum QuotationStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum BookingStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  MFS_BKASH = 'MFS_BKASH',
  MFS_NAGAD = 'MFS_NAGAD',
  CARD = 'CARD',
  CASH = 'CASH',
  ONLINE_GATEWAY = 'ONLINE_GATEWAY',
}

export enum DocumentType {
  PASSPORT = 'PASSPORT',
  PHOTO = 'PHOTO',
  NID = 'NID',
  BANK_STATEMENT = 'BANK_STATEMENT',
  AIR_TICKET = 'AIR_TICKET',
  HOTEL_VOUCHER = 'HOTEL_VOUCHER',
  VISA_COPY = 'VISA_COPY',
  OTHER = 'OTHER',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum NotificationType {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ACTION_REQUIRED = 'ACTION_REQUIRED',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum AuditAction {
  USER_REGISTER = 'USER_REGISTER',
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  APPLICATION_CREATED = 'APPLICATION_CREATED',
  APPLICATION_UPDATED = 'APPLICATION_UPDATED',
  APPLICATION_STATUS_CHANGED = 'APPLICATION_STATUS_CHANGED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  DOCUMENT_VERIFIED = 'DOCUMENT_VERIFIED',
  DOCUMENT_ACCESSED = 'DOCUMENT_ACCESSED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  QUOTATION_CREATED = 'QUOTATION_CREATED',
  QUOTATION_STATUS_CHANGED = 'QUOTATION_STATUS_CHANGED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_STATUS_CHANGED = 'BOOKING_STATUS_CHANGED',
}
