import {
  ApplicantType,
  AppointmentBookingType,
  DocumentCategory,
  ProcessingTimeUnit,
  VisaCategory,
  VisaEntryType,
} from '../../modules/visas/enums/visa-service.enum';

export const SEED_COUNTRIES = [
  {
    name: 'United Kingdom',
    slug: 'united-kingdom',
    code: 'GBR',
    iso2: 'GB',
    iso3: 'GBR',
    flag: '🇬🇧',
    description: 'Apply for UK standard visitor, student, transit, and business visas.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'United States',
    slug: 'united-states',
    code: 'USA',
    iso2: 'US',
    iso3: 'USA',
    flag: '🇺🇸',
    description: 'Explore US B1/B2 tourist, F-1 student, and C-1 transit visas with expert consular support.',
    continent: 'North America',
    isPopular: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Canada',
    slug: 'canada',
    code: 'CAN',
    iso2: 'CA',
    iso3: 'CAN',
    flag: '🇨🇦',
    description: 'Visitor visas, Super Visas for parents/grandparents, and study permits for Canada.',
    continent: 'North America',
    isPopular: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'France (Schengen)',
    slug: 'france',
    code: 'FRA',
    iso2: 'FR',
    iso3: 'FRA',
    flag: '🇫🇷',
    description: 'Short-stay Schengen visas allowing unrestricted travel across 29 European member states.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Germany (Schengen)',
    slug: 'germany',
    code: 'DEU',
    iso2: 'DE',
    iso3: 'DEU',
    flag: '🇩🇪',
    description: 'Schengen business, trade fair, and tourist visas for Germany and Europe.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Italy (Schengen)',
    slug: 'italy',
    code: 'ITA',
    iso2: 'IT',
    iso3: 'ITA',
    flag: '🇮🇹',
    description: 'Tourist and cultural Schengen visas for Rome, Milan, Venice, and Florence.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Switzerland (Schengen)',
    slug: 'switzerland',
    code: 'CHE',
    iso2: 'CH',
    iso3: 'CHE',
    flag: '🇨🇭',
    description: 'Alpine leisure, executive summit, and Schengen holiday visas for Switzerland.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Spain (Schengen)',
    slug: 'spain',
    code: 'ESP',
    iso2: 'ES',
    iso3: 'ESP',
    flag: '🇪🇸',
    description: 'Spanish Schengen visas for holidays in Madrid, Barcelona, and the Mediterranean coast.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 8,
  },
  {
    name: 'United Arab Emirates',
    slug: 'united-arab-emirates',
    code: 'ARE',
    iso2: 'AE',
    iso3: 'ARE',
    flag: '🇦🇪',
    description: 'Fast 30-day and 60-day Dubai tourist e-visas with rapid embassy approval.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 9,
  },
  {
    name: 'Saudi Arabia',
    slug: 'saudi-arabia',
    code: 'SAU',
    iso2: 'SA',
    iso3: 'SAU',
    flag: '🇸🇦',
    description: '1-Year multiple-entry tourist and Umrah e-visas with instant digital issuance.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: 'Qatar',
    slug: 'qatar',
    code: 'QAT',
    iso2: 'QA',
    iso3: 'QAT',
    flag: '🇶🇦',
    description: 'Hayya tourist eVisa and business entry permits for Doha and Qatar.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 11,
  },
  {
    name: 'Turkey',
    slug: 'turkey',
    code: 'TUR',
    iso2: 'TR',
    iso3: 'TUR',
    flag: '🇹🇷',
    description: 'Electronic e-visa and sticker visas for Istanbul, Cappadocia, and Antalya.',
    continent: 'Europe',
    isPopular: true,
    isActive: true,
    sortOrder: 12,
  },
  {
    name: 'Malaysia',
    slug: 'malaysia',
    code: 'MYS',
    iso2: 'MY',
    iso3: 'MYS',
    flag: '🇲🇾',
    description: 'Convenient Malaysian tourist eVisa with 30-day single/multiple entry allowances.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 13,
  },
  {
    name: 'Singapore',
    slug: 'singapore',
    code: 'SGP',
    iso2: 'SG',
    iso3: 'SGP',
    flag: '🇸🇬',
    description: 'Singapore authorized agent e-visa submissions with streamlined processing.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 14,
  },
  {
    name: 'Thailand',
    slug: 'thailand',
    code: 'THA',
    iso2: 'TH',
    iso3: 'THA',
    flag: '🇹🇭',
    description: 'Single-entry 60-day tourist visas and multi-entry holiday permits for Thailand.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 15,
  },
  {
    name: 'Japan',
    slug: 'japan',
    code: 'JPN',
    iso2: 'JP',
    iso3: 'JPN',
    flag: '🇯🇵',
    description: 'Short-term single and multiple entry sightseeing visas for Tokyo, Kyoto, and beyond.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 16,
  },
  {
    name: 'South Korea',
    slug: 'south-korea',
    code: 'KOR',
    iso2: 'KR',
    iso3: 'KOR',
    flag: '🇰🇷',
    description: 'C-3 short term tourist visas and electronic travel authorization for Seoul.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 17,
  },
  {
    name: 'China',
    slug: 'china',
    code: 'CHN',
    iso2: 'CN',
    iso3: 'CHN',
    flag: '🇨🇳',
    description: 'L-category tourist, M-category business, and X-category student visas for China.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 18,
  },
  {
    name: 'Australia',
    slug: 'australia',
    code: 'AUS',
    iso2: 'AU',
    iso3: 'AUS',
    flag: '🇦🇺',
    description: 'Subclass 600 visitor visas and Subclass 500 student visas for Australia.',
    continent: 'Oceania',
    isPopular: true,
    isActive: true,
    sortOrder: 19,
  },
  {
    name: 'New Zealand',
    slug: 'new-zealand',
    code: 'NZL',
    iso2: 'NZ',
    iso3: 'NZL',
    flag: '🇳🇿',
    description: 'Visitor Visa and NZeTA electronic travel authority for New Zealand.',
    continent: 'Oceania',
    isPopular: true,
    isActive: true,
    sortOrder: 20,
  },
  {
    name: 'Egypt',
    slug: 'egypt',
    code: 'EGY',
    iso2: 'EG',
    iso3: 'EGY',
    flag: '🇪🇬',
    description: 'Electronic tourist eVisas for the Pyramids, Cairo, Nile cruises, and Red Sea resorts.',
    continent: 'Africa',
    isPopular: false,
    isActive: true,
    sortOrder: 21,
  },
  {
    name: 'Indonesia (Bali)',
    slug: 'indonesia',
    code: 'IDN',
    iso2: 'ID',
    iso3: 'IDN',
    flag: '🇮🇩',
    description: 'B211A 60-day tourist visa and e-VoA for Bali, Jakarta, and Komodo islands.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 22,
  },
  {
    name: 'Vietnam',
    slug: 'vietnam',
    code: 'VNM',
    iso2: 'VN',
    iso3: 'VNM',
    flag: '🇻🇳',
    description: '90-Day multiple-entry tourist eVisa for Hanoi, Da Nang, and Ho Chi Minh City.',
    continent: 'Asia',
    isPopular: true,
    isActive: true,
    sortOrder: 23,
  },
];

export const SEED_VISA_TYPES = [
  {
    name: 'Tourist Visa',
    slug: 'tourist-visa',
    category: VisaCategory.TOURIST,
    description: 'For holiday travel, tourism, sightseeing, visiting friends and leisure trips.',
    icon: 'compass',
    isActive: true,
    sortOrder: 1,
  },
  {
    name: 'Business Visa',
    slug: 'business-visa',
    category: VisaCategory.BUSINESS,
    description: 'For commercial meetings, conferences, corporate negotiations, and trade fairs.',
    icon: 'briefcase',
    isActive: true,
    sortOrder: 2,
  },
  {
    name: 'Student Visa',
    slug: 'student-visa',
    category: VisaCategory.STUDENT,
    description: 'For pursuing higher education, language courses, and accredited academic programs.',
    icon: 'graduation-cap',
    isActive: true,
    sortOrder: 3,
  },
  {
    name: 'Family & Visit Visa',
    slug: 'family-visit-visa',
    category: VisaCategory.FAMILY_VISIT,
    description: 'For visiting relatives, family members, or long-term family reunification.',
    icon: 'users',
    isActive: true,
    sortOrder: 4,
  },
  {
    name: 'Religious & Umrah Visa',
    slug: 'religious-umrah-visa',
    category: VisaCategory.RELIGIOUS_UMRAH,
    description: 'For performing Umrah pilgrimage and visiting holy sites in the Kingdom of Saudi Arabia.',
    icon: 'sparkles',
    isActive: true,
    sortOrder: 5,
  },
  {
    name: 'Transit Visa',
    slug: 'transit-visa',
    category: VisaCategory.TRANSIT,
    description: 'For temporary airport layovers and passing through international customs zones.',
    icon: 'plane',
    isActive: true,
    sortOrder: 6,
  },
  {
    name: 'Medical Treatment Visa',
    slug: 'medical-treatment-visa',
    category: VisaCategory.MEDICAL,
    description: 'For receiving specialized medical care, surgeries, or clinical treatments abroad.',
    icon: 'activity',
    isActive: true,
    sortOrder: 7,
  },
  {
    name: 'Work & Employment Visa',
    slug: 'work-visa',
    category: VisaCategory.WORK,
    description: 'For sponsored professional employment, skilled labor, and overseas assignments.',
    icon: 'hammer',
    isActive: true,
    sortOrder: 8,
  },
];

export const SEED_VISA_SERVICES_TEMPLATE = [
  // --------------------------------------------------------------------------
  // 1. UNITED KINGDOM (Multiple Types)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'united-kingdom',
    visaTypeSlug: 'tourist-visa',
    name: 'UK Standard Visitor Visa (6 Months)',
    slug: 'uk-standard-visitor-visa-6-months',
    shortDescription:
      'Official 6-month multiple entry visitor visa for holiday, business meetings, and visiting relatives in the UK.',
    description:
      'The UK Standard Visitor Visa permits travel across England, Scotland, Wales, and Northern Ireland for tourism, family visits, business conferences, and short-term study (up to 30 days). Our specialized visa concierge manages your online UKVI profile, document validation, VFS slot booking, and financial file preparation.',
    validity: '6 Months',
    stayDuration: 'Up to 180 Days per visit',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: {
      minDays: 10,
      maxDays: 15,
      unit: ProcessingTimeUnit.DAYS,
      description: '10-15 working days following biometric appointment at VFS Global.',
    },
    recommendedApplyBefore: 'At least 6-8 weeks prior to intended departure date',
    fees: {
      government: 145,
      service: 55,
      total: 200,
      currency: 'USD',
      breakdown: [
        { name: 'UKVI Government Embassy Fee', amount: 145 },
        { name: 'Agency Processing & Concierge Fee', amount: 55 },
      ],
    },
    eligibility: [
      'Genuine intention to leave the UK at the end of the visit.',
      'Sufficient financial funds to cover all travel, accommodation, and personal expenses without recourse to public funds.',
      'Documented evidence of strong social, professional, or economic ties to the home country.',
      'No intention to undertake unauthorized paid employment or study beyond allowed thresholds.',
    ],
    prerequisites: [
      'Original current passport valid for at least 6 months beyond intended UK departure with minimum 2 blank pages.',
      'All previous old passports showing historic travel records.',
      'Official proof of employment or registered business ownership.',
      'Bank statement covering the preceding 6 consecutive months.',
    ],
    documents: [
      {
        name: 'Original Passport & Past Passports',
        description: 'Current valid passport plus all previous cancelled passports.',
        category: DocumentCategory.IDENTIFICATION,
        required: true,
        applicableFor: [ApplicantType.ALL],
        instructions: 'Must have at least 6 months validity from departure date.',
        acceptedFormats: ['PDF', 'JPG'],
      },
      {
        name: '6-Month Bank Statements & Solvency Certificate',
        description: 'Original bank statement with official branch seal and solvency letter.',
        category: DocumentCategory.FINANCIAL,
        required: true,
        applicableFor: [ApplicantType.ALL],
        instructions: 'Consistent closing balance without sudden unexplained large deposits.',
        acceptedFormats: ['PDF'],
      },
      {
        name: 'Employer NOC & Salary Certificate',
        description: 'Letter signed by HR/Company Director detailing designation and approved leave dates.',
        category: DocumentCategory.EMPLOYMENT,
        required: true,
        applicableFor: [ApplicantType.EMPLOYED],
        instructions: 'Must be on official corporate letterhead with company seal.',
        acceptedFormats: ['PDF'],
      },
      {
        name: 'Trade License & Business Registration',
        description: 'Certified Trade License, MOA, and Certificate of Incorporation for company owners.',
        category: DocumentCategory.EMPLOYMENT,
        required: true,
        applicableFor: [ApplicantType.SELF_EMPLOYED],
        acceptedFormats: ['PDF'],
      },
      {
        name: 'Student ID Card & Leave Approval',
        description: 'Official enrollment letter from school/university approving leave during travel.',
        category: DocumentCategory.OTHER,
        required: true,
        applicableFor: [ApplicantType.STUDENT],
        acceptedFormats: ['PDF'],
      },
      {
        name: 'Confirmed Round-Trip Flight & Hotel Bookings',
        description: 'Provisional flight itinerary and confirmed accommodation reservation vouchers.',
        category: DocumentCategory.TRAVEL,
        required: true,
        applicableFor: [ApplicantType.ALL],
        acceptedFormats: ['PDF'],
      },
    ],
    requirements: {
      passport: { minValidityMonths: 6, blankPages: 2, previousPassportsRequired: true },
      financial: { required: true, statementsMonths: 6, sponsorAllowed: true },
      biometrics: { required: true, description: 'Mandatory in-person biometrics at VFS Global.' },
      interview: { required: false, description: 'Interviews are rare for tourist category.' },
      appointment: { required: true, bookingType: AppointmentBookingType.ONLINE },
    },
    applicationSteps: [
      { stepNumber: 1, title: 'Complete the Application', description: 'Fill out the official online form with our guided assistance ensuring zero errors.' },
      { stepNumber: 2, title: 'Upload Documents', description: 'Securely upload your verified documents to our portal for final review before submission.' },
      { stepNumber: 3, title: 'Biometrics Appointment', description: 'Attend a visa application centre to provide your fingerprints and photograph.' },
      { stepNumber: 4, title: 'Receive Decision', description: 'Get your passport back with the visa vignette, typically within 3 weeks of your appointment.' },
    ],
    importantNotes: [
      'Embassy processing fees are non-refundable regardless of the consular decision.',
      'Priority fast-track processing (5 working days) is available for an additional consular surcharge.',
    ],
    faqs: [
      { question: 'Can I visit Scotland and Wales with this visa?', answer: 'Yes, the UK standard visitor visa is valid throughout England, Scotland, Wales, and Northern Ireland.' },
      { question: 'Is travel insurance mandatory for the UK?', answer: 'While not legally mandatory at application submission, comprehensive international travel health insurance is strongly advised.' },
    ],
    applicationCenter: {
      name: 'VFS Global UK Visa Application Centre',
      address: 'Delta Life Tower, Plot 37, Road 90, Gulshan North, Dhaka 1212',
      workingHours: 'Sunday to Thursday: 08:30 AM - 04:30 PM',
      phone: '+8809606777888',
    },
    optionalServices: [
      { name: 'VFS Priority 5-Day Processing Assistance', description: 'Fast-track slot scheduling and priority queue indexing.', fee: 320, isDefault: false },
      { name: 'Comprehensive Travel Health Insurance', description: '$50,000 global emergency medical coverage.', fee: 40, isDefault: true },
    ],
    isFeatured: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    countrySlug: 'united-kingdom',
    visaTypeSlug: 'student-visa',
    name: 'UK Student Visa (Tier 4 / CAS Route)',
    slug: 'uk-student-visa-tier-4',
    shortDescription: 'Full-time accredited university degree and higher education study visa with work entitlement.',
    description: 'Complete student visa consular assistance for university admits holding Confirmation of Acceptance for Studies (CAS). Includes financial verification, TB testing guidance, and immigration health surcharge (IHS) calculation.',
    validity: 'Course Duration + 4 Months',
    stayDuration: 'Full duration of academic study',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 15, maxDays: 20, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 620, service: 120, total: 740, currency: 'USD' },
    eligibility: ['Unconditional offer letter and valid CAS from licensed UK Sponsor.', 'Proof of funds covering 1-year tuition plus 9-month maintenance.'],
    prerequisites: ['Valid CAS letter', 'IELTS / PTE Academic score', 'TB Test certificate'],
    documents: [
      { name: 'CAS Statement', category: DocumentCategory.LEGAL, required: true, applicableFor: [ApplicantType.STUDENT] },
      { name: '28-Day Bank Statement', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.STUDENT] },
    ],
    requirements: { biometrics: { required: true }, financial: { required: true, statementsMonths: 1 } },
    applicationSteps: [
      { stepNumber: 1, title: 'CAS & Financial Check', description: 'Verify CAS details and ensure funds are held for 28 consecutive days.' },
      { stepNumber: 2, title: 'UKVI Submission', description: 'File the student application and calculate Immigration Health Surcharge.' },
      { stepNumber: 3, title: 'Biometrics & Passport Submission', description: 'Attend VFS Global appointment.' },
    ],
    importantNotes: ['IHS fee is calculated per year of study and paid upfront to the UK NHS.'],
    faqs: [{ question: 'Can students work in the UK?', answer: 'Degree students can work up to 20 hours per week during term time and full-time during holidays.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 2,
  },

  // --------------------------------------------------------------------------
  // 2. UNITED STATES (Multiple Types)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'united-states',
    visaTypeSlug: 'tourist-visa',
    name: 'US B1/B2 Tourist & Business Non-Immigrant Visa (5 Years)',
    slug: 'us-b1-b2-tourist-and-business-visa',
    shortDescription: '5-Year multiple-entry non-immigrant visa for tourism, holidays, business meetings, and medical consultations in the USA.',
    description: 'The US B1/B2 Visa is a versatile 5-year multiple-entry visa. Our agency provides comprehensive DS-160 application filing, consular appointment scheduling, profile optimization, financial verification, and interview coaching.',
    validity: 'Up to 5 Years',
    stayDuration: 'Up to 6 Months (180 Days) per entry',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 3, maxDays: 5, unit: ProcessingTimeUnit.DAYS, description: 'Passport issuance within 3-5 days after consular interview.' },
    recommendedApplyBefore: '3-6 months in advance due to consular interview scheduling queues',
    fees: { government: 185, service: 65, total: 250, currency: 'USD' },
    eligibility: ['Intention to enter the US temporarily for legitimate tourist or business purposes.', 'Binding social, economic, and family ties to country of residence.'],
    prerequisites: ['Valid passport', 'Completed Form DS-160 confirmation barcode', 'MRV Embassy fee receipt'],
    documents: [
      { name: 'Form DS-160 Confirmation Page', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Consular Interview Appointment Confirmation', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, interview: { required: true }, appointment: { required: true, bookingType: AppointmentBookingType.ONLINE } },
    applicationSteps: [
      { stepNumber: 1, title: 'DS-160 Form Filing', description: 'Complete the extensive DS-160 online consular questionnaire with our specialists.' },
      { stepNumber: 2, title: 'Fee Payment & Scheduling', description: 'Pay the MRV embassy fee and secure earliest available consular appointment.' },
      { stepNumber: 3, title: 'Interview Preparation', description: 'Engage in a 1-on-1 mock interview session covering questions and document presentation.' },
      { stepNumber: 4, title: 'Embassy Interview', description: 'Attend the interview at the US Embassy consular section.' },
    ],
    importantNotes: ['The consular officer makes the final determination during the personal interview.'],
    faqs: [{ question: 'How long can I stay on each trip?', answer: 'The US Customs and Border Protection (CBP) officer typically grants a stay of up to 6 months per entry.' }],
    applicationCenter: { name: 'Embassy of the United States Consular Section', address: 'Madani Avenue, Baridhara, Dhaka 1212' },
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 3,
  },

  // --------------------------------------------------------------------------
  // 3. CANADA
  // --------------------------------------------------------------------------
  {
    countrySlug: 'canada',
    visaTypeSlug: 'tourist-visa',
    name: 'Canada Visitor Visa (V-1 Multiple Entry)',
    slug: 'canada-visitor-visa-v1',
    shortDescription: 'Multiple entry tourist and visitor visa valid up to 10 years or until passport expiry.',
    description: 'Travel across Canada to explore Banff, Toronto, Vancouver, Montreal, and Niagara Falls. Our IRCC portal experts prepare your Statement of Purpose (SOP), family ties documentation, and financial portfolio.',
    validity: 'Up to 10 Years (or passport expiry)',
    stayDuration: 'Up to 6 Months per entry',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 20, maxDays: 35, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 140, service: 60, total: 200, currency: 'USD' },
    eligibility: ['Valid passport', 'Strong proof of employment and home ties', 'Clean background with biometric enrollment'],
    prerequisites: ['Original passport', 'Digital biometric enrollment at VFS', 'IRCC portal account submission'],
    documents: [
      { name: 'Passport & Travel History', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Purpose of Travel & Detailed Itinerary', category: DocumentCategory.TRAVEL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Proof of Financial Solvency (6 Months)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, financial: { required: true, statementsMonths: 6 } },
    applicationSteps: [
      { stepNumber: 1, title: 'IRCC Online Application', description: 'Prepare SOP, financial proof, and upload digital documents.' },
      { stepNumber: 2, title: 'Biometrics Instruction Letter (BIL)', description: 'Attend VFS Global to record biometric data.' },
      { stepNumber: 3, title: 'Passport Request (PPR)', description: 'Submit physical passport upon approval for visa stamping.' },
    ],
    importantNotes: ['Biometrics are valid for 10 years once enrolled.'],
    faqs: [{ question: 'Is the Canadian visa multiple entry?', answer: 'Yes, almost all standard visitor visas issued by IRCC are multiple entry.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 4,
  },

  // --------------------------------------------------------------------------
  // 4. FRANCE & SCHENGEN STATES
  // --------------------------------------------------------------------------
  {
    countrySlug: 'france',
    visaTypeSlug: 'tourist-visa',
    name: 'France Schengen Short-Stay Tourist Visa (Type C)',
    slug: 'schengen-france-tourist-short-stay-visa',
    shortDescription: 'Uniform Schengen visa for unrestricted travel across 29 European countries for up to 90 days.',
    description: 'Experience Paris, the French Riviera, and the entire Schengen area. We handle France-Visas portal filing, TLScontact appointment booking, flight reservations, and Schengen-compliant insurance.',
    validity: 'Up to 90 Days within 180 Days',
    stayDuration: 'Up to 90 Days',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 15, maxDays: 20, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 95, service: 55, total: 150, currency: 'USD' },
    eligibility: ['France must be the main destination or first port of entry into the Schengen Area.', 'Travel medical insurance covering minimum €30,000.'],
    prerequisites: ['Schengen medical insurance', 'TLScontact biometrics', 'Confirmed hotel vouchers'],
    documents: [
      { name: 'Schengen Travel Insurance (€30,000 minimum)', category: DocumentCategory.TRAVEL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Hotel Bookings & Travel Plan', category: DocumentCategory.ACCOMMODATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Bank Statement (6 Months)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, travelInsurance: { required: true, minCoverage: 30000, currency: 'EUR' } },
    applicationSteps: [
      { stepNumber: 1, title: 'France-Visas Registration', description: 'Submit digital application on the official French consular portal.' },
      { stepNumber: 2, title: 'TLScontact Appointment', description: 'Submit physical documents and fingerprints.' },
      { stepNumber: 3, title: 'Visa Vignette Collection', description: 'Receive passport with approved Schengen visa.' },
    ],
    importantNotes: ['Valid across all 29 Schengen member states without internal border checks.'],
    faqs: [{ question: 'Can I visit Germany or Italy with a France Schengen visa?', answer: 'Yes, as long as France is your main destination or first entry point.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 5,
  },

  // --------------------------------------------------------------------------
  // 5. UNITED ARAB EMIRATES (UAE)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'united-arab-emirates',
    visaTypeSlug: 'tourist-visa',
    name: 'Dubai (UAE) 30-Day Tourist eVisa',
    slug: 'dubai-uae-tourist-evisa-30-days',
    shortDescription: '100% digital 30-day single entry tourist eVisa issued by GDRFA with fast 48-hour approval.',
    description: 'Instant paperless Dubai tourist visa for exploring Burj Khalifa, Dubai Marina, Abu Dhabi, and desert safaris. Simple scan of passport and photograph with 2-day delivery.',
    validity: '60 Days from issuance date',
    stayDuration: '30 Days from entry date',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 2, maxDays: 3, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 110, service: 30, total: 140, currency: 'USD' },
    eligibility: ['Clear passport photo and color scan of passport bio page.'],
    prerequisites: ['Passport valid for minimum 6 months'],
    documents: [
      { name: 'Passport Bio-Page Color Scan', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Passport Size Photo (White Background)', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { passport: { minValidityMonths: 6, blankPages: 1 }, biometrics: { required: false }, interview: { required: false } },
    applicationSteps: [
      { stepNumber: 1, title: 'Submit Passport Scan', description: 'Upload clear scans of your passport and photograph.' },
      { stepNumber: 2, title: 'GDRFA Processing', description: 'Our licensed Dubai agent submits directly to UAE immigration.' },
      { stepNumber: 3, title: 'Download PDF eVisa', description: 'Receive your approved PDF visa directly via email/WhatsApp.' },
    ],
    importantNotes: ['Can be extended inside UAE for an additional 30 days.'],
    faqs: [{ question: 'Do I need to visit an embassy?', answer: 'No, UAE tourist visas are 100% online and paperless.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 6,
  },

  // --------------------------------------------------------------------------
  // 6. SAUDI ARABIA (Tourist & Umrah)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'saudi-arabia',
    visaTypeSlug: 'religious-umrah-visa',
    name: 'Saudi Arabia 1-Year Multiple Entry Tourist & Umrah eVisa',
    slug: 'saudi-arabia-tourist-and-umrah-evisa',
    shortDescription: 'Official 1-year multiple entry digital visa for performing Umrah and exploring Riyadh, Jeddah, and AlUla.',
    description: 'Instant electronic visa permitting multiple entries into Saudi Arabia for tourism, business meetings, visiting family, and performing Umrah at Makkah and Madinah.',
    validity: '1 Year (365 Days)',
    stayDuration: 'Up to 90 Days per visit',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 1, maxDays: 2, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 140, service: 35, total: 175, currency: 'USD' },
    eligibility: ['Open for eligible nationalities or holders of valid US, UK, or Schengen visas.'],
    prerequisites: ['Passport with at least 6 months validity'],
    documents: [
      { name: 'Passport Bio-Data Page Scan', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Recent Digital Photograph', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: false }, interview: { required: false } },
    applicationSteps: [
      { stepNumber: 1, title: 'Online Form Submission', description: 'Submit passport copy and basic traveler details.' },
      { stepNumber: 2, title: 'Instant MOFA Issuance', description: 'Direct issuance through Saudi Ministry of Foreign Affairs.' },
      { stepNumber: 3, title: 'Receive Digital Visa', description: 'Approved PDF e-visa delivered within 24 to 48 hours.' },
    ],
    importantNotes: ['Includes mandatory Saudi medical health insurance coverage.'],
    faqs: [{ question: 'Can women perform Umrah on this tourist visa?', answer: 'Yes, women of all ages can travel for Umrah without a Mahram on the tourist eVisa.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 7,
  },

  // --------------------------------------------------------------------------
  // 7. MALAYSIA
  // --------------------------------------------------------------------------
  {
    countrySlug: 'malaysia',
    visaTypeSlug: 'tourist-visa',
    name: 'Malaysia 30-Day Tourist eVisa',
    slug: 'malaysia-tourist-evisa-30-days',
    shortDescription: 'Official Malaysian Immigration electronic visa with 3-day turnaround for Kuala Lumpur and Penang holidays.',
    description: 'Fast digital eVisa for holidaymakers exploring Kuala Lumpur, Langkawi, and Sabah. We manage full submission through the official Malaysian eVisa portal.',
    validity: '90 Days from issuance',
    stayDuration: 'Up to 30 Days',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 2, maxDays: 4, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 45, service: 25, total: 70, currency: 'USD' },
    eligibility: ['Valid passport', 'Confirmed return ticket', 'Proof of accommodation'],
    prerequisites: ['Passport copy', 'Digital photo 35x50mm', 'Flight reservation'],
    documents: [
      { name: 'Passport Copy', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Confirmed Return Air Ticket', category: DocumentCategory.TRAVEL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Hotel Reservation', category: DocumentCategory.ACCOMMODATION, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: false }, interview: { required: false } },
    applicationSteps: [
      { stepNumber: 1, title: 'Upload Travel Details', description: 'Provide flight itinerary and passport scan.' },
      { stepNumber: 2, title: 'Immigration Clearance', description: 'Malaysian Immigration processes and approves the file.' },
      { stepNumber: 3, title: 'Print eVisa', description: 'Receive A4 color printable eVisa.' },
    ],
    importantNotes: ['Must carry printed colored copy of the eVisa and return ticket upon arrival.'],
    faqs: [{ question: 'Do I need to submit physical passport?', answer: 'No, the Malaysian eVisa is completely electronic.' }],
    optionalServices: [],
    isFeatured: false,
    isActive: true,
    sortOrder: 8,
  },

  // --------------------------------------------------------------------------
  // 8. SINGAPORE
  // --------------------------------------------------------------------------
  {
    countrySlug: 'singapore',
    visaTypeSlug: 'tourist-visa',
    name: 'Singapore Authorized Agent Tourist e-Visa',
    slug: 'singapore-tourist-e-visa',
    shortDescription: 'Singapore Immigration & Checkpoints Authority (ICA) electronic entry visa via authorized visa agent.',
    description: 'Official Singapore entry visa processed through ICA SAVE portal by accredited travel agents. Perfect for Marina Bay, Universal Studios, and corporate visits.',
    validity: '30 to 60 Days',
    stayDuration: 'Up to 30 Days per visit',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 3, maxDays: 5, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 35, service: 35, total: 70, currency: 'USD' },
    eligibility: ['Valid passport with at least 6 months validity', 'Confirmed flight and hotel details'],
    prerequisites: ['Form 14A completed', 'Letter of Introduction (LOI) if applicable'],
    documents: [
      { name: 'Completed Form 14A', category: DocumentCategory.LEGAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Passport Bio-Data Page', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Bank Statement (3 Months)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: false }, interview: { required: false } },
    applicationSteps: [
      { stepNumber: 1, title: 'Complete Form 14A', description: 'Sign and submit Form 14A with passport copy.' },
      { stepNumber: 2, title: 'ICA System Submission', description: 'Agency submits via Singapore SAVE portal.' },
      { stepNumber: 3, title: 'Electronic Delivery', description: 'Receive digital PDF visa with QR code.' },
    ],
    importantNotes: ['Also complete the SG Arrival Card (SGAC) 3 days before travel.'],
    faqs: [{ question: 'Is the Singapore visa valid for multiple entries?', answer: 'Yes, most tourist e-visas issued are multiple entry.' }],
    optionalServices: [],
    isFeatured: false,
    isActive: true,
    sortOrder: 9,
  },

  // --------------------------------------------------------------------------
  // 9. THAILAND
  // --------------------------------------------------------------------------
  {
    countrySlug: 'thailand',
    visaTypeSlug: 'tourist-visa',
    name: 'Thailand 60-Day Single Entry Tourist Visa (TR)',
    slug: 'thailand-tourist-single-entry-visa',
    shortDescription: 'Official 60-day tourist visa for Bangkok, Phuket, Pattaya, and Chiang Mai holidays.',
    description: 'Relax in tropical Thailand with our complete Royal Thai Embassy visa service. Includes file auditing, embassy liaison, and sticker visa processing.',
    validity: '90 Days from issuance',
    stayDuration: '60 Days (extendable by 30 days in Thailand)',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 5, maxDays: 7, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 40, service: 25, total: 65, currency: 'USD' },
    eligibility: ['Proof of minimum $700 financial balance per traveler.', 'Confirmed round-trip flights and hotel bookings.'],
    prerequisites: ['Original passport', 'Bank statement with minimum required balance', 'Employment/Student proof'],
    documents: [
      { name: 'Original Passport', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Bank Statement & Solvency Certificate', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'NOC / Business Trade License', category: DocumentCategory.EMPLOYMENT, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { passport: { minValidityMonths: 6, blankPages: 2 }, financial: { required: true, minBalance: 700 } },
    applicationSteps: [
      { stepNumber: 1, title: 'Document Verification', description: 'Review bank balance and travel reservations.' },
      { stepNumber: 2, title: 'Embassy Submission', description: 'Submit passport to Royal Thai Embassy consular section.' },
      { stepNumber: 3, title: 'Passport Delivery', description: 'Collect passport with official Thai sticker visa.' },
    ],
    importantNotes: ['Can be extended for another 30 days at any local Thai immigration bureau.'],
    faqs: [{ question: 'Can I extend my stay in Thailand?', answer: 'Yes, you can apply for a 30-day extension at immigration for 1,900 THB.' }],
    optionalServices: [],
    isFeatured: false,
    isActive: true,
    sortOrder: 10,
  },

  // --------------------------------------------------------------------------
  // 10. JAPAN
  // --------------------------------------------------------------------------
  {
    countrySlug: 'japan',
    visaTypeSlug: 'tourist-visa',
    name: 'Japan Short-Term Sightseeing Visa (Single/Multiple)',
    slug: 'japan-short-term-sightseeing-visa',
    shortDescription: 'Short-term single and multiple entry tourist visa for Tokyo, Mt. Fuji, Kyoto, and Osaka.',
    description: 'Experience cherry blossoms, vibrant Tokyo metropolis, and historic Kyoto temples with our Japan consular filing service. Full itinerary, tax certificate, and bank solvency support.',
    validity: '90 Days (Single) or up to 3 Years (Multiple)',
    stayDuration: '15 to 30 Days per visit',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 7, maxDays: 10, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 30, service: 45, total: 75, currency: 'USD' },
    eligibility: ['Detailed day-by-day travel schedule.', 'Sufficient funds demonstrated via 6-month bank statement.'],
    prerequisites: ['Original passport', 'Detailed itinerary schedule', 'Income tax certificate'],
    documents: [
      { name: 'Day-by-Day Schedule of Stay', category: DocumentCategory.TRAVEL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Bank Statement (6 Months)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Income Tax Return (ITR)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.EMPLOYED, ApplicantType.SELF_EMPLOYED] },
    ],
    requirements: { passport: { minValidityMonths: 6, blankPages: 2 }, financial: { required: true, statementsMonths: 6 } },
    applicationSteps: [
      { stepNumber: 1, title: 'Itinerary Planning', description: 'Structure your detailed daily Japan schedule of stay.' },
      { stepNumber: 2, title: 'VFS Japan Submission', description: 'Submit physical documents to Japan Visa Application Centre.' },
      { stepNumber: 3, title: 'Visa Vignette Stamping', description: 'Collect passport with Japan visa.' },
    ],
    importantNotes: ['The Japanese Embassy requires exact hotel details and daily movement plans.'],
    faqs: [{ question: 'Can I apply for a 3-year multiple entry visa?', answer: 'Yes, if you meet financial requirements and have previous OECD travel history.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 11,
  },

  // --------------------------------------------------------------------------
  // 11. AUSTRALIA
  // --------------------------------------------------------------------------
  {
    countrySlug: 'australia',
    visaTypeSlug: 'tourist-visa',
    name: 'Australia Visitor Visa (Subclass 600 Tourist Stream)',
    slug: 'australia-visitor-visa-subclass-600',
    shortDescription: 'Electronic Australian visitor visa for holidays, sightseeing, and visiting family in Sydney, Melbourne, and Brisbane.',
    description: 'Explore the Great Barrier Reef, Sydney Opera House, and the Outback. We handle your complete ImmiAccount digital application, GTE criteria, financial documentation, and biometric scheduling.',
    validity: 'Up to 12 Months',
    stayDuration: 'Up to 3 Months (or 12 Months) per visit',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 15, maxDays: 25, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 130, service: 70, total: 200, currency: 'USD' },
    eligibility: ['Genuine Temporary Entrant (GTE) criteria satisfied.', 'Sufficient funds to support yourself during your stay in Australia.'],
    prerequisites: ['Original passport', 'ImmiAccount online submission', 'Biometrics at Australian Visa Application Centre'],
    documents: [
      { name: 'Passport Bio-Page & Stamps', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Financial Proof & Bank Statements', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Evidence of Employment or Business', category: DocumentCategory.EMPLOYMENT, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, financial: { required: true, statementsMonths: 6 } },
    applicationSteps: [
      { stepNumber: 1, title: 'ImmiAccount Filing', description: 'Submit digital application through Australian Department of Home Affairs.' },
      { stepNumber: 2, title: 'Biometrics Enrollment', description: 'Visit VFS Global for digital photo and fingerprints.' },
      { stepNumber: 3, title: 'Grant Notification', description: 'Receive official electronic Visa Grant Notice via email.' },
    ],
    importantNotes: ['Australian visas are 100% label-free and digitally linked to your passport.'],
    faqs: [{ question: 'Do I need a visa label in my passport?', answer: 'No, Australia issues digital electronic visa grant notices.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 12,
  },

  // --------------------------------------------------------------------------
  // 12. TURKEY
  // --------------------------------------------------------------------------
  {
    countrySlug: 'turkey',
    visaTypeSlug: 'tourist-visa',
    name: 'Turkey Tourist Sticker & eVisa',
    slug: 'turkey-tourist-visa',
    shortDescription: 'Discover Istanbul, Cappadocia hot air balloons, and Mediterranean Antalya with our consular filing assistance.',
    description: 'Complete Turkish sticker visa and eVisa support. We manage gateway appointment scheduling, travel insurance, hotel bookings, and consular file preparation.',
    validity: 'Up to 90 Days',
    stayDuration: 'Up to 30 Days',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 7, maxDays: 10, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 90, service: 40, total: 130, currency: 'USD' },
    eligibility: ['Valid passport', 'Confirmed travel itinerary and flight bookings', 'Bank statement with 6-month transaction history'],
    prerequisites: ['Passport with 6 months validity', 'Gateway Globe appointment'],
    documents: [
      { name: 'Original Passport', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: '6-Month Bank Statement', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Employment NOC / Trade License', category: DocumentCategory.EMPLOYMENT, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, financial: { required: true, statementsMonths: 6 } },
    applicationSteps: [
      { stepNumber: 1, title: 'File Preparation', description: 'Verify financial files, leave letter, and confirmed reservations.' },
      { stepNumber: 2, title: 'Gateway Submission', description: 'Submit passport and fingerprints at Turkey Visa Application Center.' },
      { stepNumber: 3, title: 'Passport Return', description: 'Collect passport with Turkish sticker visa.' },
    ],
    importantNotes: ['Holders of valid US, UK, or Schengen visas can obtain an instant online Turkish eVisa.'],
    faqs: [{ question: 'Can I get an eVisa if I hold a US visa?', answer: 'Yes, travelers with valid US, UK, or Schengen visas can obtain instant electronic eVisas.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 13,
  },

  // --------------------------------------------------------------------------
  // 13. INDONESIA (BALI)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'indonesia',
    visaTypeSlug: 'tourist-visa',
    name: 'Indonesia (Bali) B211A 60-Day Tourist eVisa',
    slug: 'indonesia-bali-tourist-evisa-60-days',
    shortDescription: '60-Day single entry electronic tourist visa for Bali, Jakarta, Lombok, and Raja Ampat.',
    description: 'Explore Bali temples, surfing beaches, and Ubud waterfalls. 100% online eVisa with option to extend twice for up to a total of 180 days stay.',
    validity: '90 Days from issuance',
    stayDuration: '60 Days (Extendable in Indonesia)',
    entryType: VisaEntryType.SINGLE,
    processingTime: { minDays: 3, maxDays: 5, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 75, service: 35, total: 110, currency: 'USD' },
    eligibility: ['Passport with at least 6 months validity', 'Bank balance statement of at least $2,000'],
    prerequisites: ['Passport bio-page scan', 'Digital photo', 'Financial statement'],
    documents: [
      { name: 'Passport Bio-Page Scan', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Recent Color Photo', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Proof of Funds (Minimum $2,000)', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: false }, financial: { required: true, minBalance: 2000 } },
    applicationSteps: [
      { stepNumber: 1, title: 'Online Document Upload', description: 'Submit your passport scan and proof of funds.' },
      { stepNumber: 2, title: 'Indonesian Immigration Approval', description: 'Processed through the official Molina portal.' },
      { stepNumber: 3, title: 'Receive PDF eVisa', description: 'Electronic visa sent directly to your inbox.' },
    ],
    importantNotes: ['Can be extended twice for 60 days each while staying in Bali.'],
    faqs: [{ question: 'Can I extend this visa in Bali?', answer: 'Yes, this B211A visa allows up to two 60-day extensions at local immigration offices.' }],
    optionalServices: [],
    isFeatured: false,
    isActive: true,
    sortOrder: 14,
  },

  // --------------------------------------------------------------------------
  // 14. VIETNAM
  // --------------------------------------------------------------------------
  {
    countrySlug: 'vietnam',
    visaTypeSlug: 'tourist-visa',
    name: 'Vietnam 90-Day Multiple Entry Tourist eVisa',
    slug: 'vietnam-tourist-evisa-90-days',
    shortDescription: 'Official electronic tourist visa for 90 days multiple entries across Hanoi, Halong Bay, and Ho Chi Minh City.',
    description: 'Fast 3-day turnaround online eVisa issued directly by the Vietnam National Administration of Tourism and Immigration Department.',
    validity: '90 Days',
    stayDuration: 'Up to 90 Days',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 3, maxDays: 4, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 50, service: 25, total: 75, currency: 'USD' },
    eligibility: ['Passport with at least 6 months validity', 'Clear portrait photo and passport scan'],
    prerequisites: ['Digital passport scan', 'Passport size photo'],
    documents: [
      { name: 'Passport Bio-Page Scan', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Digital Portrait Photo (4x6 cm)', category: DocumentCategory.IDENTIFICATION, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: false }, interview: { required: false } },
    applicationSteps: [
      { stepNumber: 1, title: 'Upload Passport & Photo', description: 'Provide passport details and digital image.' },
      { stepNumber: 2, title: 'Immigration Processing', description: 'Submitted directly to Vietnam Immigration Department.' },
      { stepNumber: 3, title: 'Download Official eVisa', description: 'Download PDF with official barcode for entry.' },
    ],
    importantNotes: ['Enter and exit through any of the 33 international airports and border gates.'],
    faqs: [{ question: 'Can I enter Vietnam multiple times with this visa?', answer: 'Yes, this 90-day visa permits unlimited multiple entries within the validity period.' }],
    optionalServices: [],
    isFeatured: false,
    isActive: true,
    sortOrder: 15,
  },

  // --------------------------------------------------------------------------
  // 15. GERMANY (Business)
  // --------------------------------------------------------------------------
  {
    countrySlug: 'germany',
    visaTypeSlug: 'business-visa',
    name: 'Germany Schengen Business & Trade Fair Visa',
    slug: 'germany-schengen-business-visa',
    shortDescription: 'Short-stay Schengen business visa for corporate meetings, trade exhibitions in Frankfurt/Hannover/Munich, and negotiations.',
    description: 'Expedited business visa handling for attending European trade exhibitions, conferences, and executive client negotiations in Germany and across Schengen states.',
    validity: 'Up to 90 Days',
    stayDuration: 'Up to 90 Days',
    entryType: VisaEntryType.MULTIPLE,
    processingTime: { minDays: 10, maxDays: 15, unit: ProcessingTimeUnit.DAYS },
    fees: { government: 95, service: 65, total: 160, currency: 'USD' },
    eligibility: ['Formal invitation letter from host German company or trade fair ticket.'],
    prerequisites: ['German invitation letter', 'Company sponsorship letter', 'Schengen medical insurance'],
    documents: [
      { name: 'Official German Business Invitation Letter', category: DocumentCategory.EMPLOYMENT, required: true, applicableFor: [ApplicantType.EMPLOYED, ApplicantType.SELF_EMPLOYED] },
      { name: 'Company Sponsoring Letter & Bank Statement', category: DocumentCategory.FINANCIAL, required: true, applicableFor: [ApplicantType.ALL] },
      { name: 'Schengen Medical Insurance (€30,000)', category: DocumentCategory.TRAVEL, required: true, applicableFor: [ApplicantType.ALL] },
    ],
    requirements: { biometrics: { required: true }, travelInsurance: { required: true, minCoverage: 30000, currency: 'EUR' } },
    applicationSteps: [
      { stepNumber: 1, title: 'Business Dossier Compilation', description: 'Verify invitation, company trade license, and cover letters.' },
      { stepNumber: 2, title: 'VFS Germany Biometrics', description: 'Submit physical dossier and biometrics.' },
      { stepNumber: 3, title: 'Receive Business Visa', description: 'Collect passport with Schengen business visa.' },
    ],
    importantNotes: ['Covers travel to all 29 European Schengen member states.'],
    faqs: [{ question: 'Can I visit other Schengen countries on this German business visa?', answer: 'Yes, you can travel freely across the entire Schengen Zone during your stay.' }],
    optionalServices: [],
    isFeatured: true,
    isActive: true,
    sortOrder: 16,
  },
];
